name: Build PR Documentation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: 1
  UV_TORCH_BACKEND: auto

jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: "kit/package-lock.json"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup environment
        run: |
          pip install --upgrade pip uv
          uv pip install .[onnxruntime] accelerate diffusers timm
          uv pip install git+https://github.com/huggingface/doc-builder

      - name: Make documentation
        shell: bash
        run: |
          make doc BUILD_DIR=onnx-doc-build VERSION=pr_${{ env.PR_NUMBER }}
          echo ${{ env.COMMIT_SHA }} > onnx-doc-build/commit_sha
          echo ${{ env.PR_NUMBER }} > onnx-doc-build/pr_number

      - uses: actions/upload-artifact@v4
        with:
          name: doc-build-artifact
          path: onnx-doc-build/
