name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

env:
  UV_SYSTEM_PYTHON: 1
  UV_TORCH_BACKEND: auto

jobs:
  build_documentation:
    runs-on: ubuntu-22.04
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache-dependency-path: "kit/package-lock.json"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set environment variables
        run: |
          cd optimum
          version=`echo "$(grep '^__version__ =' onnx/version.py | cut -d '=' -f 2 | xargs)"`

          if [[ $version == *.dev0 ]]
          then
            echo "VERSION=main" >> $GITHUB_ENV
          else
            echo "VERSION=v$version" >> $GITHUB_ENV
          fi

          cd ..

      - name: Setup environment
        run: |
          pip install --upgrade pip uv
          uv pip install .[onnxruntime] accelerate diffusers timm
          uv pip install git+https://github.com/huggingface/doc-builder

      - name: Make documentation
        run: |
          make doc BUILD_DIR=onnx-doc-build VERSION=${{ env.VERSION }}

      - name: Push documentation
        run: |
          cd onnx-doc-build
          doc-builder push optimum-onnx \
            --doc_build_repo_id "hf-doc-build/doc-build" \
            --token "${{ secrets.HF_DOC_BUILD_PUSH }}" \
            --commit_msg "Updated with commit $COMMIT_SHA See: https://github.com/huggingface/optimum-onnx/commit/$COMMIT_SHA" \
            --n_retries 5
